
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import { PrivacyGuard } from '@/components/PrivacyGuard';

export const metadata: Metadata = {
  title: "Anuska's Digital Portfolio",
  description: 'A personal portfolio for Anuska Dasgupta, generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentYear = new Date().getFullYear();

  return (
    <html lang="en" className="!scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <PrivacyGuard />
        {children}
        <Toaster />
        <footer className="w-full p-4 text-center text-sm text-muted-foreground">
          Copyright © {currentYear} Anuska Dasgupta. All Rights Reserved. Content on this site is protected and may not be copied or downloaded.
        </footer>
      </body>
    </html>
  );
}
